---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bluerose
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
#base-image: ghcr.io/ublue-os/silverblue-main
#image-version: 41 # latest is also supported if you want new updates ASAP
base-image: quay.io/almalinuxorg/almalinux-bootc
image-version: 10-kitten

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    install:
      packages:
        - epel-release

  - type: script
    snippets:
      - "/usr/bin/crb enable"

  - type: dnf
    install:
      packages:
        - "@kde-desktop-environment"

  - type: dnf
    group-install:
      packages:
        - "KDE Plasma Workspaces"

  - type: script
    snippets:
      - "/usr/bin/systemctl enable sddm"

  - type: script
    snippets:
      - "/usr/bin/systemctl set-default graphical.target"

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

